### PR TITLE
Fix conjugation for verbs ending with -ie

### LINKED ISSUE #54: Conjugation for verbs ending with -ie (progressive aspect)
https://github.com/rossmeissl/verbs/pull/50#discussion_r547297253

```ruby
irb(main):001:0> Verbs::Conjugator.conjugate(:lie, aspect: :progressive, tense: :past)
=> "was liying"
irb(main):002:0> Verbs::Conjugator.conjugate(:lie, aspect: :progressive)
=> "is liying"
```

### PR DESCRIPTION
**Pull request by nerixim**
fixes #54

### CODE REVIEW

**Review by rossmeissl — APPROVED** [review]
Thanks @nerixim !

File: lib/verbs/conjugator.rb [hunk 1]
```diff
@@ -193,7 +193,7 @@ def present_participle(infinitive)
       when /(^be|ye|oe|nge|ee)$/
         infinitive.to_s
       when /ie$/
-        "#{infinitive.to_s[0..-2]}y"
```
Comment (nerixim) [inline lib/verbs/conjugator.rb:196]: @rossmeissl negative index here was confusing (for me?) so replaced it with `gsub`.

```ruby
irb(main):004:0> 'die'[0..-2]
=> "di"
```

Confusing when you have a Python background.
```python
>>> 'die'[0:-2]
'd'
```
